apiVersion: apps/v1
kind: Deployment

metadata:
  name: frontend-blue
  namespace: ecommerce

spec:
  replicas: 1

  selector:
    matchLabels:
      app: frontend
      version: blue

  template:
    metadata:
      labels:
        app: frontend
        version: blue

    spec:
      containers:
      - name: frontend

        image: 046819497518.dkr.ecr.eu-west-2.amazonaws.com/ecommerce-frontend:latest

        imagePullPolicy: Always

        ports:
        - containerPort: 80