name: Frontend CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-2

    - name: Login to Amazon ECR
      run: |
        aws ecr get-login-password --region eu-west-2 | docker login --username AWS --password-stdin 046819497518.dkr.ecr.eu-west-2.amazonaws.com

    - name: Build frontend image
      run: |
        docker build -t ecommerce-frontend ./client

    - name: Tag image
      run: |
        docker tag ecommerce-frontend:latest 046819497518.dkr.ecr.eu-west-2.amazonaws.com/ecommerce-frontend:latest

    - name: Push image to ECR
      run: |
        docker push 046819497518.dkr.ecr.eu-west-2.amazonaws.com/ecommerce-frontend:latest

    - name: Deploy to EKS
      run: |
        aws eks update-kubeconfig --region eu-west-2 --name ecommerce-cluster
        kubectl rollout restart deployment frontend-blue -n ecommerce